### PR TITLE
Increase Timeouts - fixes #85

### LINKED ISSUE #85: Client times out after 60 seconds, preventing download of larger packages
I selected everything, but:
"Download Failed
It looks like the backend server may have gone down while you were here. Try again later."

BTW, could you provide an "Everything package" on mediafire/google drive/dropbox/mega to save server load?

### PR DESCRIPTION
**Pull request by znxDomain**
Increase the server and client timeouts so large zipfiles can be compressed and successfully downloaded.  Tested with retroarch packages.  Fixes #85

### CODE REVIEW

File: SDSetupBackend/Controllers/v1.cs [hunk 1]
```diff
@@ -86,7 +86,7 @@ public class v1 : ControllerBase {
                     DeletingFileStream stream = (DeletingFileStream) ZipFromFilestreams(files.ToArray(), uuid);
 
                     Program.generatedZips[uuid] = stream;
-                    stream.Timeout(30000);
+                    stream.Timeout(180000);
```
Comment (noahc3) [inline SDSetupBackend/Controllers/v1.cs]: I don't want zips sitting on the server for 3 minutes if they aren't going to be downloaded.

Comment (znxDomain) [reply SDSetupBackend/Controllers/v1.cs]: That's fine.  The problem I was seeing and that this fixed, is that zips, especially with retroarch in them, were taking up to 160 second to build.

Comment (noahc3) [reply SDSetupBackend/Controllers/v1.cs]: The timeout doesn't start until after the zip is built. The 30 seconds is just waiting for the browser to start the download.
